# Generated by Django 5.2.17 on 2026-08-15 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProveedorAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor', models.CharField(max_length=150)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proveedor_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['proveedor'],
                'unique_together': {('user', 'proveedor')},
            },
        ),
    ]
