# Generated by Django 5.2.17 on 2026-08-15 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_proveedoraccess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('PROVEEDOR', 'Proveedor'), ('SUPERVISOR', 'Supervisor'), ('DIRECTOR', 'Director'), ('ADMIN', 'Administrador')], default='PROVEEDOR', max_length=20),
        ),
    ]
