# Generated by Django 5.2.17 on 2026-08-15 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendedorAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendedor', models.CharField(max_length=150)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendedor_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['vendedor'],
                'unique_together': {('user', 'vendedor')},
            },
        ),
    ]
