# Generated by Django 5.2.17 on 2026-08-10 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('closings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='closing',
            name='closed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='closings', to=settings.AUTH_USER_MODEL),
        ),
    ]
