# Generated by Django 5.2.17 on 2026-08-18 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoPrecioSap',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cod_producto', models.CharField(max_length=50)),
                ('nombre_producto', models.CharField(max_length=255)),
                ('cod_grupo', models.CharField(blank=True, max_length=20, null=True)),
                ('proveedor', models.CharField(blank=True, max_length=150, null=True)),
                ('bodega', models.CharField(blank=True, max_length=50, null=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('iva', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('ultima_vez_visto', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'productos_precios_sap',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('cod_sap', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('vendedor', models.CharField(blank=True, max_length=44, null=True)),
                ('estado', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vendedores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VentaDetalle',
            fields=[
                ('pk', models.CompositePrimaryKey('id_interno_documento', 'numero_linea', blank=True, editable=False, primary_key=True, serialize=False)),
                ('id_interno_documento', models.IntegerField()),
                ('numero_linea', models.IntegerField()),
                ('alm', models.CharField(blank=True, max_length=10, null=True)),
                ('cantidad', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('cod_producto', models.CharField(blank=True, max_length=50, null=True)),
                ('cod_cliente', models.CharField(blank=True, max_length=50, null=True)),
                ('cod_transportador', models.CharField(blank=True, max_length=50, null=True)),
                ('descuento_porcentaje', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('id_picking', models.IntegerField(blank=True, null=True)),
                ('indicador_impuestos', models.CharField(blank=True, max_length=20, null=True)),
                ('iva', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('nit_cliente', models.CharField(blank=True, max_length=20, null=True)),
                ('nom_cliente', models.CharField(blank=True, max_length=200, null=True)),
                ('numero_documento', models.IntegerField(blank=True, null=True)),
                ('precio_un_sin_dcto', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('producto', models.CharField(blank=True, max_length=255, null=True)),
                ('proveedor', models.CharField(blank=True, max_length=150, null=True)),
                ('tipologia_cliente', models.CharField(blank=True, max_length=255, null=True)),
                ('venta_bruta', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('unidad_medida', models.CharField(blank=True, max_length=20, null=True)),
                ('vendedor_nombre', models.CharField(blank=True, max_length=150, null=True)),
                ('numero_ref', models.IntegerField(blank=True, null=True)),
                ('icui', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('cant_nc', models.IntegerField(blank=True, null=True)),
                ('line_total_nc', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('iva_nc', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('concepto_nc', models.CharField(blank=True, max_length=255, null=True)),
                ('nc_vinculada', models.CharField(blank=True, max_length=100, null=True)),
                ('total_cant_final', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('line_total_final', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total_iva_final', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
            ],
            options={
                'db_table': 'ventas_detalle',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VentaDetalleVal',
            fields=[
                ('pk', models.CompositePrimaryKey('id_interno_documento', 'numero_linea', blank=True, editable=False, primary_key=True, serialize=False)),
                ('id_interno_documento', models.IntegerField()),
                ('numero_linea', models.IntegerField()),
                ('alm', models.CharField(blank=True, max_length=10, null=True)),
                ('cantidad', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('cod_producto', models.CharField(blank=True, max_length=50, null=True)),
                ('cod_cliente', models.CharField(blank=True, max_length=50, null=True)),
                ('cod_transportador', models.CharField(blank=True, max_length=50, null=True)),
                ('descuento_porcentaje', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('id_picking', models.IntegerField(blank=True, null=True)),
                ('indicador_impuestos', models.CharField(blank=True, max_length=20, null=True)),
                ('iva', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('nit_cliente', models.CharField(blank=True, max_length=20, null=True)),
                ('nom_cliente', models.CharField(blank=True, max_length=200, null=True)),
                ('numero_documento', models.IntegerField(blank=True, null=True)),
                ('precio_un_sin_dcto', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('producto', models.CharField(blank=True, max_length=255, null=True)),
                ('proveedor', models.CharField(blank=True, max_length=150, null=True)),
                ('tipologia_cliente', models.CharField(blank=True, max_length=255, null=True)),
                ('venta_bruta', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('unidad_medida', models.CharField(blank=True, max_length=20, null=True)),
                ('vendedor_nombre', models.CharField(blank=True, max_length=150, null=True)),
                ('numero_ref', models.IntegerField(blank=True, null=True)),
                ('icui', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('cant_nc', models.IntegerField(blank=True, null=True)),
                ('line_total_nc', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('iva_nc', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('concepto_nc', models.CharField(blank=True, max_length=255, null=True)),
                ('nc_vinculada', models.CharField(blank=True, max_length=100, null=True)),
                ('total_cant_final', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('line_total_final', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total_iva_final', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
            ],
            options={
                'db_table': 'ventas_detalle_val',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PivotSavedView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('config', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pivot_saved_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='VendedorPresupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendedor', models.CharField(max_length=150, unique=True)),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['vendedor'],
            },
        ),
    ]
