# Generated by Django 5.2.17 on 2026-08-21 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mirror', '0003_premiotier'),
    ]

    operations = [
        migrations.AddField(
            model_name='pivotsavedview',
            name='cerrado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pivotsavedview',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pivotsavedview',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
