# Generated by Django 5.2.17 on 2026-08-21 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mirror', '0004_pivotsavedview_cerrado_pivotsavedview_fecha_fin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pivotsavedview',
            name='presupuestos',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
