# Generated by Django 5.2.17 on 2026-08-21 18:11
"""Siembra `PivotSavedView.presupuestos` (nuevo campo, antes inexistente) con
una copia de los valores que ya estaban en el default global
(VendedorPresupuesto) al momento de introducir el campo, para que las tablas
guardadas existentes no pierdan de golpe su presupuesto/cumplimiento/premio
mostrado. De aqui en adelante cada tabla es independiente (ver
PivotSavedViewSet.set_presupuesto)."""
from django.db import migrations


def backfill_presupuestos(apps, schema_editor):
    PivotSavedView = apps.get_model('mirror', 'PivotSavedView')
    VendedorPresupuesto = apps.get_model('mirror', 'VendedorPresupuesto')

    montos_por_vendedor = {p.vendedor: str(p.monto) for p in VendedorPresupuesto.objects.all()}
    if not montos_por_vendedor:
        return

    for view in PivotSavedView.objects.all():
        result = view.result or {}
        rows_fields = result.get('rows_fields') or []
        if 'vendedor_nombre' not in rows_fields:
            continue
        idx = rows_fields.index('vendedor_nombre')

        presupuestos = {}
        for entry in result.get('data') or []:
            row = entry.get('row') or []
            if len(row) <= idx:
                continue
            vendedor = row[idx]
            if vendedor in montos_por_vendedor:
                presupuestos[vendedor] = montos_por_vendedor[vendedor]

        if presupuestos:
            view.presupuestos = presupuestos
            view.save(update_fields=['presupuestos'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('mirror', '0005_pivotsavedview_presupuestos'),
    ]

    operations = [
        migrations.RunPython(backfill_presupuestos, noop_reverse),
    ]
