# Generated by Django 5.2.17 on 2026-08-21 18:59

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mirror', '0006_backfill_presupuestos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pivotsavedview',
            name='presupuestos',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='pivotsavedview',
            name='result',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
    ]
