# Generated by Django 5.2.17 on 2026-08-26 02:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mirror', '0007_alter_pivotsavedview_presupuestos_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaestraCliente',
            fields=[
                ('pk', models.CompositePrimaryKey('mes_maestra', 'cod_cliente', 'unidad', blank=True, editable=False, primary_key=True, serialize=False)),
                ('mes_maestra', models.CharField(max_length=6)),
                ('cod_cliente', models.TextField()),
                ('unidad', models.TextField()),
                ('nombre', models.TextField(blank=True, null=True)),
                ('negocio', models.TextField(blank=True, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('telefono', models.BigIntegerField(blank=True, null=True)),
                ('cod_vendedor', models.IntegerField(blank=True, null=True)),
                ('vendedor', models.CharField(blank=True, max_length=60, null=True)),
                ('dia_visita', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'maestra_clientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DiaHabil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('es_habil', models.BooleanField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['fecha'],
            },
        ),
    ]
